/**
 * Created by Devin on 5/3/2024.
 */
/*
Global with sharing class Five9Api {

   // @Future(Callout=true)
    //public static void TaskToVoiceCall(String TaskJsonString) {


        //Post VoiceCall Object from Task Fields to Salesforce

       // Callout PostVC = Five9Handler.PostVCtoSF(TaskJsonString);

      //  HttpResponse res = HttpCallout.process(PostVC.toString());
        //res.getBody();

        //Login to Five9



    }
}
*/