/**
 * Created by Devin on 5/3/2024.
 */
/*
Global with sharing class Five9Handler {

    //first Callout
   // public static Callout PostVCtoSF(String TaskJsonString){

       // String endpoint = 'test';
//String PostUrl = 'test1';

       // Callout PostVC = new Callout((String) TaskJsonString, (String)endpoint, (String) PostUrl);

//return PostVC;
  //  }

   // public static void Five9Login(){

   // }

}
*/