/**
 * Created by Devin on 5/3/2024.
 */
/*
Global class Callout {
    private static final Integer DEFAULT_TIMEOUT = 10000;

    public Callout(String jsonString,
            String endpoint,
            String method,
            Integer millisecondTimeout) {
        this.BodyString = jsonString;
        this.Endpoint = endpoint;
        this.method = method;
        this.Timeout = millisecondTimeout;
    }

    public Callout(String jsonString, String endpoint, String method) {
        this(jsonString, endpoint, method, DEFAULT_TIMEOUT);
    }

    // sometimes an api key is supplied as part of the URL ...
    // because it's not always necessary, we make it a public member of the class
    public String ApiKey { get; set; }

    public String BodyString { get; private set; }
    public String Endpoint { get; private set; }
    public String method { get; private set; }
    public Integer Timeout { get; private set; }
}
*/