/**
 * Created by Devin on 5/3/2024.
 */
/*
Global class HttpCallout {

   // public static HttpResponse process(String calloutString) {
       //Callout calloutObj = (Callout)JSON.deserialize(calloutString, Callout.class);
        // req = setupHttpRequest(calloutObj);
        // this is the part you would try/catch
        // in a more robust implementation ...
      //  HttpResponse res = makeRequest(req);
//return res;
   // }

  //  private static HttpRequest setupHttpRequest(Callout callout) {
    //   HttpRequest req = new HttpRequest();
    ///    req.setEndpoint(callout.Endpoint);
      //  req.setMethod(callout.method);
     //   req.setTimeout(callout.Timeout);
       // req.setHeader('Content-Type', 'application/json');
   //     req.setBody(callout.BodyString);
     //   if(String.isNotBlank(callout.ApiKey)) {
     //       req.setHeader('x-api-key', callout.ApiKey);
    /////    }
     //   return req;
  ///  }

    @TestVisible
    private static HttpResponse makeRequest(HttpRequest req) {
        return new Http().send(req);
    }

}
*/